name: Atividade 02.2 – Acrescentando novas etapas ao workflow

on:
  push:

jobs:    
    
    segundo-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Primeiro passo"
            - name: checkout
              uses: actions/checkout@v5
            - name: Lista arquivos
              run: ls ${{ github.workspace }}
            - name: Data
              run: date
            - name: Hora
              run: date +%T
            - name: Sistema operacional
              run: uname -a
            - name: Versão do Git
              run: git --version
            - name: Readme
              run: cat README.md
            - name: Arquivos do projeto
              run: ls -R