name: Quinto Workflow

on:
  push:

jobs:
    primeiro-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Primeiro passo"
            - name: checkout
              uses: actions/checkout@v5
            - name: Checkout
              run: checkout
            - name: Data
              run: date
            - name: Versão do Git
              run: git --version
    segundo-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Segundo passo"
            - name: checkout
              uses: actions/checkout@v5
            - name: Verificando se existe README.md
              run: 
                test -f README.md
            - name: Verificando se existe LICENSE
              run: 
                test -f LICENSE
            - name: Verificando se existe .gitignore
              run: 
                test -f .gitignore